### ISSUE TITLE
Readme suggestions

### ISSUE THREAD

**Issue by reagle** [STealthy-and-haSTy/EnhancedSnippets#2]
- include full example of wind with options snippet (XML or YAML)
- fix odd space in `sublime- snippet` (multiple)
- modify to include package name: "and select the package `EnhancedSnippets` from the list:"
- remove close bracket in example: "laborum.]"
- instead of `-source` as example scope, use a real scope.
- in YAML examples, perhaps quote strings to avoid issues

**Comment by reagle** [comment]
FYI: complete wind snippet:

```
---
tabTrigger: wind
scope: text.html - (meta.tag | meta.characer.less-than) - source.php
description: Windstorm HTML Template
options:
  - field: 2
    placeholder: 'Windstorm Version Number'
    values:
      - latest
      - 0.1.9
      - 0.1.10
---
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>$1</title>
</head>
<body>
  <!-- Docs: https://axel669.github.io/lib.windstorm/ -->
  <script src="https://cdn.jsdelivr.net/npm/@axel669/windstorm@${2:latest}/dist/browser.js"></script>

  $0
</body>
</html>
```

**Comment by OdatNurd** [comment]
Thanks for the feedback! All have been onboarded except the one regarding `-source` as a scope, since that is actually a valid scope. However, the windstorm snippet is now present as an example and includes a more complex scope as a demonstration.
