### ISSUE TITLE
Unwanted space during expansion

### ISSUE THREAD

**Issue by reagle** [STealthy-and-haSTy/EnhancedSnippets#8]
Following up from #6 , when I select a value I see a unwanted space before the parens: `raiseValueError ("")`. After some toying around, I notice it happens _before_ the option is selected.

![enhanced-snippet-stuff](https://github.com/STealthy-and-haSTy/EnhancedSnippets/assets/596814/8dee3b3c-6fda-4059-828d-df94a2bb7a51)

Interestingly, in a new Python file, the problem doesn't arise.

![enhanced-snippet-empty](https://github.com/STealthy-and-haSTy/EnhancedSnippets/assets/596814/67e1d1ca-4055-47fa-b7c5-f014bfbca971)

This made me think it's an interaction with an auto-formatter, and indeed, removing [sublack](https://packagecontrol.io/packages/sublack) solves the issue. So my guess is that sublack is doing some autoformatting while ES is awaiting the selection of an option.

**Comment by OdatNurd** [comment]
In that case I'm going to close this issue; there's not a lot that I can do to generically block other plugins from making modifications.

**Comment by reagle** [comment]
Thinking about this further, I have sublack set to autoformat on save, which occurs when I press `cmd+s` or step away from the buffer, which is configured to autosave.

I could confirm sublack is invoked during ES by including some single quotes which sublack will convert to double quotes. I'd then wonder is there a way to turn off autosave while ES is doing its thing? However, I can test this presently because of #9 .

**Comment by reagle** [comment]
With #9 magic-fixing itself, I can confirm sublack is running when ES gives its selection modal; however, I'm no longer getting the spurious space, so another magic-fix!
